name: Branch CI

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0
    
    - name: Install Valgrind
      run: sudo apt-get update && sudo apt-get install valgrind 
    
    - name: Run Tests without Valgrind
      run: make test-run

    - name: Run Tests with Valgrind
      run: make test-run-val
